bind_address = "127.0.0.1:3000"
oauth_redirect_uri = "http://localhost:3000/auth/google/callback"
oauth_client_secret_path = "client_secret.apps.googleusercontent.com.json"
admin_emails = ["jschaab@gmail.com"]
user_emails = []
secure_cookies = false
gpu_device_index = 0
telemetry_retention_days = 30
log_level_console = "warn"
log_level_file = "info"
log_level_memory = "debug"
log_file_name = "server.log"

[database]
url = "wss://surrealdb.lan:443"
jwt_file_path = "database.jwt"
namespace = "mini_inference_engine"
database = "main"
