import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Bypasses the Axum backend entirely.
 * Intercepts browser requests and serves the raw HTML/JS/CSS files from the disk.
 */
async function mockStaticAssets(page) {
    const basePath = __dirname;

    // Mock HTML routes
    const routes = {
        '/': 'index.html',
        '/memory': 'memory.html',
        '/models': 'models.html',
        '/settings': 'settings.html',
        '/stats': 'stats.html',
        '/console': 'console.html',
    };

    for (const [routePath, file] of Object.entries(routes)) {
        await page.route(routePath, route => {
            route.fulfill({
                contentType: 'text/html',
                body: fs.readFileSync(path.join(basePath, file))
            });
        });
    }

    // Mock CSS & JS assets
    await page.route('**/css/*.css', route => {
        const file = route.request().url().split('/').pop();
        route.fulfill({ contentType: 'text/css', body: fs.readFileSync(path.join(basePath, file)) });
    });

    await page.route('**/js/*.js', route => {
        const file = route.request().url().split('/').pop();
        route.fulfill({ contentType: 'application/javascript', body: fs.readFileSync(path.join(basePath, file)) });
    });
}

/**
 * Mocks the Engine's JSON API responses to simulate a healthy, fully loaded GPU system.
 */
async function mockEngineApis(page) {
    await page.route('**/api/status', route => {
        route.fulfill({
            status: 200,
            json: {
                active_chat_model_id: 'mock-model-1',
                active_backend: 'Candle',
                benchmark_running: false,
                vram_total: 16000000000,
                vram_used: 8000000000,
                models_vram: [],
                vram_events: [],
                ram_events: []
            }
        });
    });

    await page.route('**/api/models', route => {
        route.fulfill({
            status: 200,
            json: [
                { id: 'mock-model-1', name: 'Mock Chat Model', roles: ['GeneralChat'], supported_backends: ['Candle'], arch: 'Llama', parameters_billions: 8.0, size_on_disk_gb: 4.0, max_context_len: 8192, provenance: {} },
                { id: 'mock-comp-1', name: 'Mock Compressor', roles: ['ContextCompressor'], supported_backends: ['Candle'], arch: 'XLMRoberta', parameters_billions: 0.5, size_on_disk_gb: 1.0, max_context_len: 1024, provenance: {} }
            ]
        });
    });

    await page.route('**/api/console/loglevel', route => {
        // Grant console access to the UI by mocking a successful 200 OK
        route.fulfill({ status: 200, json: { level: 'info' } });
    });
}

test.describe('Mini Inference Engine - UI Functionality', () => {
    test.beforeEach(async ({ page }) => {
        await mockStaticAssets(page);
        await mockEngineApis(page);
    });

    test('Navbar dynamically injects and renders', async ({ page }) => {
        await page.goto('/');
        await expect(page.locator('h1')).toContainText('Mini Inference Engine');
        
        // Check if the navbar links generated by common.js exist
        const chatBtn = page.locator('button:has-text("💬 Chat")');
        await expect(chatBtn).toBeVisible();
        
        const consoleBtn = page.locator('#nav-console-btn');
        await expect(consoleBtn).toBeVisible();
    });

    test('Chat UI streams a mock generation', async ({ page }) => {
        await page.route('**/api/generate', route => {
            // Mocks the chunked HTTP stream by instantly fulfilling a single text payload
            route.fulfill({ status: 200, body: 'Hello! I am a simulated AI response.', contentType: 'text/plain' });
        });

        await page.goto('/');

        const input = page.locator('#prompt-input');
        const sendBtn = page.locator('#send-btn');
        
        await input.fill('Can you hear me?');
        await sendBtn.click();

        // Verify the DOM inserts the correct elements
        await expect(page.locator('.user-message').last()).toContainText('Can you hear me?');
        await expect(page.locator('.ai-message').last()).toContainText('Hello! I am a simulated AI response.');
        await expect(page.locator('#regen-btn')).toBeVisible();
    });

    test('Memory view tabs switch content correctly', async ({ page }) => {
        await page.goto('/memory');

        const vramTab = page.locator('.tab:has-text("GPU VRAM")');
        const ramTab = page.locator('.tab:has-text("System RAM")');
        const vramView = page.locator('#vram-view');
        const ramView = page.locator('#ram-view');

        await expect(vramTab).toHaveClass(/active/);
        await expect(vramView).toHaveClass(/active/);

        await ramTab.click();

        await expect(ramTab).toHaveClass(/active/);
        await expect(ramView).toHaveClass(/active/);
        await expect(vramView).not.toHaveClass(/active/);
    });

    test('Settings UI loads API Keys and opens generation modal', async ({ page }) => {
        await page.route('**/api/settings/keys', route => {
            if (route.request().method() === 'GET') {
                route.fulfill({ status: 200, json: [{ name: 'Test Key', hash: 'abcdef1234567890', description: 'Used for Playwright' }] });
            } else {
                route.fallback();
            }
        });

        await page.goto('/settings');

        await expect(page.locator('#keys-tbody')).toContainText('Test Key');
        await expect(page.locator('#keys-tbody')).toContainText('Used for Playwright');

        await page.locator('button:has-text("+ Create New Key")').click();
        await expect(page.locator('#new-key-modal')).toBeVisible();

        await page.locator('.btn-cancel').click();
        await expect(page.locator('#new-key-modal')).not.toBeVisible();
    });

    test('Models Directory renders the model configuration cards', async ({ page }) => {
        await page.goto('/models');
        
        const modelCards = page.locator('.model-card');
        await expect(modelCards).toHaveCount(2); // Based on our mock Apis output
        await expect(modelCards.first()).toContainText('Mock Chat Model');
    });
});